### ISSUE TITLE
can you help me debug kotlin attach in vscode (my facebook https://www.facebook.com/profile.php?id=100055844960353) 

### ISSUE THREAD

**Issue by kakashianh** [BonhyeonGu/JenaController#1]
"type": "kotlin",
            "request": "attach",
            "name": "Debug Attach",
            "hostName": "localhost",
            "projectRoot": "${workspaceFolder}",
            "port": 8000,
            "timeout": 30000
        }
    ]

**Comment by BonhyeonGu** [comment]
Sorry about that. I'm not on social media so I can't see your post, and your question is not relevant to the project, so I can't answer it.
